# Generated by Django 3.2.8 on 2021-11-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
                ('registration_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
