# Generated by Django 3.2.8 on 2021-11-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=100)),
                ('login_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
